// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkUPuVjvJAj8QbR3R340J74uEYGnlyaCg',
    appId: '1:330827985359:web:2cd6e99cb832c133a762ba',
    messagingSenderId: '330827985359',
    projectId: 'unrelo-23b2c',
    authDomain: 'unrelo-23b2c.firebaseapp.com',
    storageBucket: 'unrelo-23b2c.appspot.com',
    measurementId: 'G-X83KR5896E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCr5zI7Rw8Y8LrTSW3BWYBpjVxGWr93jJE',
    appId: '1:330827985359:android:f5bcd21468cdc0e5a762ba',
    messagingSenderId: '330827985359',
    projectId: 'unrelo-23b2c',
    storageBucket: 'unrelo-23b2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3SzYADF_bcsRw92tBHYh0cRnl704Y2Hg',
    appId: '1:330827985359:ios:0a5117d03b6d84aea762ba',
    messagingSenderId: '330827985359',
    projectId: 'unrelo-23b2c',
    storageBucket: 'unrelo-23b2c.appspot.com',
    iosClientId: '330827985359-rjq2phbno6lv7j08riq6sr1ubfhlp6u3.apps.googleusercontent.com',
    iosBundleId: 'com.example.unrelo',
  );
}
